// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHEPe0xt7Tx5fHJR4jjYm2U-yDiKpW_nk',
    appId: '1:626704167393:web:999437f30da14d7d79e2a0',
    messagingSenderId: '626704167393',
    projectId: 'myloahstudio',
    authDomain: 'myloahstudio.firebaseapp.com',
    storageBucket: 'myloahstudio.firebasestorage.app',
    measurementId: 'G-QTLLNSE862',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxAsac3No-4KQ8qqueMCnFZkts9SEAWyk',
    appId: '1:626704167393:android:8f0670ca85cf560b79e2a0',
    messagingSenderId: '626704167393',
    projectId: 'myloahstudio',
    storageBucket: 'myloahstudio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuj3RgcxiEqeHguRO9zBVx8uoTgwQIAAs',
    appId: '1:626704167393:ios:ce20bd457abd9c1b79e2a0',
    messagingSenderId: '626704167393',
    projectId: 'myloahstudio',
    storageBucket: 'myloahstudio.firebasestorage.app',
    iosBundleId: 'com.portifolio.linozeferino.loahstudio',
  );
}
