// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRIuI_dT73XToy1lIzII98qGi8Ffj6Pos',
    appId: '1:606822904099:web:41a08ca4abe7d8a349dc96',
    messagingSenderId: '606822904099',
    projectId: 'loahstudioo',
    authDomain: 'loahstudioo.firebaseapp.com',
    storageBucket: 'loahstudioo.firebasestorage.app',
    measurementId: 'G-3H35XM3WVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfiUl8hwL7usMaEATcLNCk1CABZzi0D4Q',
    appId: '1:606822904099:android:f8b7ba94ca41887549dc96',
    messagingSenderId: '606822904099',
    projectId: 'loahstudioo',
    storageBucket: 'loahstudioo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7Sim8RmlEY3kmvv2CkhYlY41LsjQngJY',
    appId: '1:606822904099:ios:22f23d451443aa1e49dc96',
    messagingSenderId: '606822904099',
    projectId: 'loahstudioo',
    storageBucket: 'loahstudioo.firebasestorage.app',
    iosBundleId: 'com.portifolio.linozeferino.loahstudio',
  );
}
